# Generated by Django 5.0.4 on 2024-04-11 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markapp', '0002_alter_student_pic_alter_teacher_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='pic',
            field=models.FileField(upload_to='markapp/media/face_pics/'),
        ),
    ]
