# Generated by Django 5.0.4 on 2024-04-11 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markapp', '0004_alter_student_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='pic',
            field=models.FileField(upload_to='face_pics/'),
        ),
        migrations.AlterField(
            model_name='teacher',
            name='pic',
            field=models.FileField(upload_to='face_pics/'),
        ),
    ]
