# Generated by Django 5.0.4 on 2024-04-12 06:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markapp', '0005_alter_student_pic_alter_teacher_pic'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contact',
            name='mail',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone_no',
        ),
    ]
