# Generated by Django 5.0.4 on 2024-04-12 06:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markapp', '0006_remove_contact_mail_remove_contact_phone_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='email',
            field=models.EmailField(default='', max_length=254),
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=' '),
        ),
    ]
