# Generated by Django 5.0.4 on 2024-04-13 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markapp', '0007_contact_email_contact_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='teacher',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
