# Generated by Django 5.0.4 on 2024-04-13 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markapp', '0009_teacher_reg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(default='a'),
        ),
    ]
