# Generated by Django 5.0.4 on 2024-04-13 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('markapp', '0012_alter_attendance_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='user',
        ),
        migrations.DeleteModel(
            name='Contact',
        ),
        migrations.RemoveField(
            model_name='student',
            name='reg',
        ),
        migrations.RemoveField(
            model_name='teacher',
            name='reg',
        ),
        migrations.DeleteModel(
            name='Attendance',
        ),
        migrations.DeleteModel(
            name='Student',
        ),
        migrations.DeleteModel(
            name='Teacher',
        ),
    ]
