# Generated by Django 5.0.4 on 2024-04-13 18:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('markapp', '0013_remove_attendance_user_delete_contact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email', models.EmailField(default='', max_length=254)),
                ('message', models.TextField(default=' ')),
            ],
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField()),
                ('status', models.CharField(default='a')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('pic', models.FileField(upload_to='face_pics/')),
                ('class_name', models.CharField(max_length=255)),
                ('contact_no', models.IntegerField()),
                ('programme', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('attendance_percent', models.IntegerField()),
                ('parent_name', models.CharField(max_length=255)),
                ('parent_contact', models.IntegerField()),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Teacher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('pic', models.FileField(upload_to='face_pics/')),
                ('date_of_join', models.DateField()),
                ('contact_no', models.IntegerField()),
                ('courses_taught', models.CharField(max_length=255)),
                ('programme', models.CharField(max_length=255)),
                ('college', models.CharField(max_length=255)),
                ('reg', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
