# Generated by Django 5.0.4 on 2024-04-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('markapp', '0016_alter_attendance_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='attendance_percent',
            field=models.DecimalField(decimal_places=3, max_digits=7),
        ),
    ]
